name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allow this workflow to be started manually from the Actions tab.
  workflow_dispatch:

# Jobs run in parallel (as default), steps are run sequentially.
jobs:
  # This workflow contains a single job called "build", if it wasn't obvious enough.
  build:
    # Use a build agent with the best operating system.
    runs-on: ubuntu-latest

    steps:
      # Check out the repository under $GITHUB_WORKSPACE, so the build agent can compile the code.
      - uses: actions/checkout@v2

      # Build using a shell script.
      - name: Build & Test
        run: ./build.sh
